[package]
name = "crab-worm"
authors = ["Mateus Batichotti <matebatichotti@gmail.com>", "Arthur Machado <@gmail.com>", "Isabelly Camilly <@gmail.com>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
description = "The Crab wORM. A Rust Object Relational Mapper."

[dependencies]
crab-worm-macros = { path = "macros" }

[workspace]
members = ["core","macros"]
