use std::collections::HashSet;

use crate::meta::{EnumMetadata, FieldMetadata, StructMetadata, TypeMetadata};

const ID_PK: &str = "\t\"id\" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";

// STRUCT

impl StructMetadata {
    pub fn to_html(&self) -> String {
        let fields: Vec<String> = self
            .fields
            .iter()
            .filter(|f| f.name != "id")
            .filter(|f| vec_inner(f.ty).is_none())
            .map(|f| field_to_html(self.name, f))
            .collect();

        if fields.is_empty() {
            return String::new();
        }

        format!(
            "<form data-table=\"{}\">\n<fieldset>\n<legend>{}</legend>\n{}\n</fieldset>\n\
             <button type=\"submit\">Save</button>\n<output class=\"status\"></output>\n</form>",
            snake_case(self.name),
            self.name,
            fields.join("\n")
        )
    }

    pub fn to_sql(&self) -> String {
        let columns: Vec<String> = self
            .fields
            .iter()
            .filter(|f| f.name != "id")
            .filter(|f| vec_inner(f.ty).is_none())
            .map(|f| single_column(&format!("{}.{}", self.name, f.name), f.name, f.ty))
            .collect();

        let children: Vec<String> = self
            .fields
            .iter()
            .filter_map(|f| vec_table_def(self.name, f))
            .collect();

        if columns.is_empty() && children.is_empty() {
            return String::new();
        }

        let mut all_columns = vec![String::from(ID_PK)];
        all_columns.extend(columns);

        let mut statements = vec![format!(
            "CREATE TABLE IF NOT EXISTS {} (\n{}\n);",
            table_name(self.name),
            all_columns.join(",\n")
        )];
        statements.extend(children);
        statements.join("\n\n")
    }
}

// ENUM

impl EnumMetadata {
    pub fn to_html(&self) -> String {
        let options: String = self
            .variants
            .iter()
            .enumerate()
            .map(|(i, v)| format!("\t<option value=\"{}\">{v}</option>\n", i + 1))
            .collect();

        format!("<select name=\"{}_id\">\n{}</select>\n", self.name, options)
    }

    pub fn to_sql(&self) -> String {
        if self.variants.is_empty() {
            return String::new();
        }

        let values = self
            .variants
            .iter()
            .enumerate()
            .map(|(i, v)| format!("({}, '{}')", i + 1, v.replace('\'', "''")))
            .collect::<Vec<_>>()
            .join(", ");

        let table = table_name(self.name);

        format!(
            "CREATE TABLE IF NOT EXISTS {table} (\n\
             \t\"id\" INTEGER PRIMARY KEY,\n\
             \t\"name\" TEXT NOT NULL UNIQUE\n\
             );\n\
             INSERT INTO {table} (\"id\", \"name\") VALUES {values}\n\
             ON CONFLICT (\"id\") DO UPDATE SET \"name\" = excluded.\"name\";"
        )
    }
}

// WRAPPER

impl TypeMetadata {
    pub fn to_html(&self) -> String {
        match self {
            Self::Struct(s) => s.to_html(),
            Self::Enum(e) => e.to_html(),
        }
    }

    pub fn to_sql(&self) -> String {
        match self {
            Self::Struct(s) => s.to_sql(),
            Self::Enum(e) => e.to_sql(),
        }
    }
}

const SUBMIT_SCRIPT: &str = r#"<script>
const API_URL = "http://localhost:3000";

function readForm(form) {
	const row = {};
	for (const el of form.querySelectorAll("input, select")) {
		if (!el.name) continue;
		if (el.type === "checkbox") row[el.name] = el.checked;
		else if (el.value === "" && !el.required) row[el.name] = null;
		else if (el.type === "number" || el.tagName === "SELECT") row[el.name] = Number(el.value);
		else row[el.name] = el.value;
	}
	return row;
}

for (const form of document.querySelectorAll("form[data-table]")) {
	const status = form.querySelector(".status");
	form.addEventListener("submit", async (event) => {
		event.preventDefault();
		status.textContent = "Saving...";
		try {
			const res = await fetch(`${API_URL}/${form.dataset.table}`, {
				method: "POST",
				headers: { "Content-Type": "application/json" },
				body: JSON.stringify(readForm(form)),
			});
			if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
			form.reset();
			status.textContent = "Saved.";
		} catch (err) {
			status.textContent = "Error: " + err.message;
		}
	});
}
</script>"#;

pub fn generate_html() -> String {
    let mut parts: Vec<String> = inventory::iter::<TypeMetadata>()
        .into_iter()
        .map(|t| t.to_html())
        .filter(|s| !s.is_empty())
        .collect();
    parts.push(SUBMIT_SCRIPT.to_string());
    parts.join("\n\n")
}

pub fn generate_sql() -> String {
    let mut all: Vec<&'static TypeMetadata> =
        inventory::iter::<TypeMetadata>.into_iter().collect();

    all.sort_by_key(|t| (matches!(t, TypeMetadata::Struct(_)), t.name()));

    let mut visited: HashSet<&'static str> = HashSet::new();
    let mut ordered: Vec<&'static TypeMetadata> = Vec::new();

    for t in &all {
        visit(t, &all, &mut visited, &mut ordered);
    }

    ordered
        .into_iter()
        .map(|t| t.to_sql())
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join("\n\n")
}

/// DFS: visita primeiro as dependencias de `t` e so depois o adiciona em `ordered`.
/// O tipo e marcado como visitado antes de descer, o que quebra ciclos.
fn visit(
    t: &'static TypeMetadata,
    all: &[&'static TypeMetadata],
    visited: &mut HashSet<&'static str>,
    ordered: &mut Vec<&'static TypeMetadata>,
) {
    if !visited.insert(t.name()) {
        return; // ja ordenado, ou em andamento (ciclo)
    }

    if let TypeMetadata::Struct(s) = t {
        for f in s.fields {
            let Some(dep_name) = dependency_name(f.ty) else {
                continue;
            };
            if let Some(dep) = all.iter().find(|x| x.name() == dep_name) {
                visit(dep, all, visited, ordered);
            }
        }
    }

    ordered.push(t);
}

fn dependency_name(ty: &str) -> Option<&'static str> {
    let t = strip_option(ty);
    let inner = match vec_inner(&t) {
        Some(v) => strip_option(&v),
        None => t,
    };

    if let Some(e) = find_enum(&inner) {
        return Some(e.name);
    }
    find_struct(&inner).map(|s| s.name)
}

// Identificadores
//
// Todo identificador vai entre aspas duplas e em snake_case. As aspas evitam
// palavras reservadas (`User` -> "user"); o snake_case evita que o Postgres
// diferencie maiusculas de minusculas. Consequencia: na hora de consultar
// a tabela no psql, escreva SELECT * FROM "user";

fn snake_case(s: &str) -> String {
    let chars: Vec<char> = s.chars().collect();
    let mut out = String::new();
    for (i, &c) in chars.iter().enumerate() {
        if c.is_uppercase() {
            let prev_lower = i > 0 && (chars[i - 1].is_lowercase() || chars[i - 1].is_ascii_digit());
            let acronym_end = i > 0
                && chars[i - 1].is_uppercase()
                && chars.get(i + 1).is_some_and(|n| n.is_lowercase());
            if prev_lower || acronym_end {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

fn quote_ident(s: &str) -> String {
    format!("\"{}\"", s.replace('"', "\"\""))
}

/// Nome (ja citado) da tabela de um tipo registrado: `User` -> `"user"`.
fn table_name(type_name: &str) -> String {
    quote_ident(&snake_case(type_name))
}

// Acessorios

fn last_segment(ty: &str) -> &str {
    ty.rsplit("::").next().unwrap_or(ty).trim()
}

fn sql_type(ty: &str) -> Option<&'static str> {
    match last_segment(ty) {
        "i8" | "i16" | "u8" => Some("SMALLINT"),
        "i32" | "u16" => Some("INTEGER"),
        "i64" | "u32" | "isize" => Some("BIGINT"),
        "u64" | "usize" => Some("NUMERIC(20,0)"),
        "i128" | "u128" => Some("NUMERIC(39,0)"),
        "bool" => Some("BOOLEAN"),
        "f32" => Some("REAL"),
        "f64" => Some("DOUBLE PRECISION"),
        "String" => Some("TEXT"),
        "char" => Some("CHAR(1)"),
        _ => None,
    }
}

fn generic_inner(ty: &str, wrapper: &str) -> Option<String> {
    let t: String = ty.split_whitespace().collect();
    let start = t.find('<')?;
    if last_segment(&t[..start]) != wrapper || !t.ends_with('>') {
        return None;
    }
    Some(t[start + 1..t.len() - 1].to_string())
}

fn vec_inner(ty: &str) -> Option<String> {
    generic_inner(ty, "Vec")
}

fn option_inner(ty: &str) -> Option<String> {
    generic_inner(ty, "Option")
}

fn strip_option(ty: &str) -> String {
    let mut t = ty.to_string();
    while let Some(inner) = option_inner(&t) {
        t = inner;
    }
    t
}

fn find_enum(ty: &str) -> Option<&'static EnumMetadata> {
    let name = last_segment(ty);
    inventory::iter::<TypeMetadata>
        .into_iter()
        .find_map(|t| match t {
            TypeMetadata::Enum(e) if e.name == name => Some(e),
            _ => None,
        })
}

fn find_struct(ty: &str) -> Option<&'static StructMetadata> {
    let name = last_segment(ty);
    inventory::iter::<TypeMetadata>
        .into_iter()
        .find_map(|t| match t {
            TypeMetadata::Struct(s) if s.name == name => Some(s),
            _ => None,
        })
}

fn single_column(field: &str, name: &str, ty: &str) -> String {
    column_def(field, name, ty, false)
}

fn column_def(field: &str, name: &str, ty: &str, nullable: bool) -> String {
    if let Some(inner) = option_inner(ty) {
        return column_def(field, name, &inner, true);
    }

    if vec_inner(ty).is_some() {
        panic!(
            "tipo nao suportado: o campo `{field}` tem tipo `{ty}`; `Vec` aninhado \
             ou dentro de `Option` nao e suportado"
        );
    }

    let not_null = if nullable { "" } else { " NOT NULL" };

    if let Some(sql) = sql_type(ty) {
        return format!("\t{} {}{}", quote_ident(name), sql, not_null);
    }
    if let Some(e) = find_enum(ty) {
        return format!(
            "\t{} INTEGER{} REFERENCES {}(\"id\")",
            quote_ident(&format!("{name}_id")),
            not_null,
            table_name(e.name)
        );
    }
    if let Some(s) = find_struct(ty) {
        return format!(
            "\t{} INTEGER{} REFERENCES {}(\"id\")",
            quote_ident(&format!("{name}_id")),
            not_null,
            table_name(s.name)
        );
    }
    panic!(
        "tipo nao registrado: o campo `{field}` tem tipo `{ty}`, que nao e um \
         escalar suportado nem possui `#[derive(crab_worm)]`"
    );
}

fn vec_table_def(parent: &str, f: &FieldMetadata) -> Option<String> {
    let inner = vec_inner(f.ty)?;
    let mut value = single_column(&format!("{}.{}", parent, f.name), "value", &inner);
    if find_struct(&strip_option(&inner)).is_some() {
        value.push_str(" ON DELETE CASCADE");
    }

    let parent_snake = snake_case(parent);
    let child_table = quote_ident(&format!("{}_{}", parent_snake, f.name));
    let parent_fk = quote_ident(&format!("{}_id", parent_snake));

    Some(format!(
        "CREATE TABLE IF NOT EXISTS {child_table} (\n\
         {ID_PK},\n\
         \t{parent_fk} INTEGER NOT NULL REFERENCES {parent_table}(\"id\") ON DELETE CASCADE,\n\
         \t\"position\" INTEGER NOT NULL,\n\
         {value}\n);",
        parent_table = table_name(parent),
    ))
}


fn field_to_html(owner: &str, field: &FieldMetadata) -> String {
    let nullable = option_inner(field.ty).is_some();
    let ty = strip_option(field.ty);
    let name = if find_enum(&ty).is_some() || find_struct(&ty).is_some() {
        format!("{}_id", field.name)
    } else {
        field.name.to_string()
    };
    let id = format!("{}_{}", snake_case(owner), name);

    let html = if let Some(e) = find_enum(&ty) {
        let mut options = String::new();

        for (i, variant) in e.variants.iter().enumerate() {
            options.push_str(&format!(
                "<option value=\"{}\">{}</option>\n",
                i + 1,
                variant
            ));
        }

        format!(
            "<select name=\"{name}\" id=\"{id}\">\n{options}</select>"
        )
    } else if find_struct(&ty).is_some() {
        format!("<select name=\"{name}\" id=\"{id}\"></select>")
    } else {
        let input = match sql_type(&ty) {
            Some("BOOLEAN") => "checkbox",
            Some("SMALLINT" | "INTEGER" | "BIGINT"
                | "NUMERIC(20,0)" | "NUMERIC(39,0)"
                | "REAL" | "DOUBLE PRECISION") => "number",
            _ => "text",
        };
        let required = if input != "checkbox" && !nullable { " required" } else { "" };

        format!(
            "<input type=\"{input}\" name=\"{name}\" id=\"{id}\"{required}>"
        )
    };

    format!(
        "<label for=\"{id}\">{}</label>\n{html}",
        field.name
    )
}
