[package]
name = "crab-worm-macros"
authors = ["Mateus Batichotti <matebatichotti@gmail.com>", "Arthur Machado <@gmail.com>", "Isabelly Camilly <@gmail.com>"]
version = "0.1.0"
edition = "2024"
license = "MIT"
readme = "README.md"
description = "The Crab wORM. A Rust Object Relational Mapper."

[lib]
proc-macro = true

[dependencies]
syn = "3"
quote = "1"
crab-worm-core = { path = "../core" }